# adapted from https://docs.readthedocs.com/platform/stable/guides/conda.html#id1
version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "miniconda3-3.12-24.9"   # see https://docs.readthedocs.com/platform/stable/guides/conda.html#making-builds-faster-with-mamba

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml
